name: release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: ^1
        cache: true
        check-latest: true
    - uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        distribution: goreleaser
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
